### ISSUE TITLE
Raw database-specific migrations are now present in the code

### ISSUE THREAD

**Issue by justabaka** [McLive/DjangoPowerDNS#10]
Hello! I'm working the current application code to allow it to use the PostgreSQL database and run in docker/kubernetes. In fact, your application worked perfectly with PostgreSQL out of the box (only needed a couple of model changes) and it should be able to run using any database if it's supported by both Django and PowerDNS, but the recent commit is preventing this: a83d9b3

I doubt your application needs this SQL code as it's shipped with PowerDNS packages in the most popular server OSes: https://pkgs.org/download/pdns . Can we have it removed or rewritten so people would explicitly state that they are willing to execite this migration in their production database according to the SQL dialect they prefer to use so we both could contribute to your project in a positive way without breaking cross compatibility?

Thank you in advance!

**Comment by McLive** [comment]
Hi!

I recently added those raw queries, because [some people](https://github.com/McLive/DjangoPowerDNS/issues/7) are somehow using this app without having a PowerDNS database setup.

Maybe it's better to just add a notice in the README file saying you need to setup a pdns databse first. 💡 

Thanks for letting me now, I'll think about it. 

PS: Do you plan to create a PR for docker stuff? I'd really appreciate it. :)

**Comment by justabaka** [comment]
Glad to hear this from you. I think this is a good idea to add a notice for people so they need to read documentation for the software they want to be using. 

P.S. Yeah I plan to create a PR once it's done in a proper way and not utilizing `python manage.py run` anymore. Also we probably need to inspect my model changes to make sure they don't break MySQL pdns: https://github.com/justabaka/DjangoPowerDNS/commit/48daf62fe810678b72e6f5f76020f17830ecf89e?diff=split#diff-dcdb806ba033c8722460ccb9a0b764f0R185 (BOOL is an ailas to TINYINT(1) so it should work fine)

**Comment by McLive** [comment]
> P.S. Yeah I plan to create a PR once it's done in a proper way and not utilizing `python manage.py run` anymore.

Awesome! 👍 



> Also we probably need to inspect my model changes to make sure they don't break MySQL pdns: [justabaka@48daf62?diff=split#diff-dcdb806ba033c8722460ccb9a0b764f0R185](https://github.com/justabaka/DjangoPowerDNS/commit/48daf62fe810678b72e6f5f76020f17830ecf89e?diff=split#diff-dcdb806ba033c8722460ccb9a0b764f0R185) (BOOL is an ailas to TINYINT(1) so it should work fine)

I just tried with my MySQL environment and it works fine. I included that in the recent commit.
