### ISSUE TITLE
bug: SOA serial out of uint32 after mass records edit/update inside zone

### ISSUE THREAD

**Issue by kotofeus-bc** [McLive/DjangoPowerDNS#13]
Today we got crush after SOA serial updated to 20190202100, That was great fault  on authorative server =(
"100" is unacceptable, because 1 more digit over size of uint32 maximum value of SOA serial.

**Comment by kotofeus-bc** [comment]
Code refer to 
https://github.com/McLive/DjangoPowerDNS/blob/2bf880f21e420b42410e41046fa71d8fe4abe3cb/dpdns/models.py#L117

**Comment by McLive** [comment]
Looks like you did a lot of changes 😮 

It will now start the timestmap from next day if there are more than 99 changes.

**Comment by kotofeus-bc** [comment]
Thanks, will try it on secondary server. 
Seems like "rule of good tone" with YYYYMMDDss take a "shoot in the foot" for zones with a lot of records (dynamic records etc.).
Maybe will right choice switch SOA serial to unix timestamp?

**Comment by McLive** [comment]
Yeah unix timestamps seem like a good idea. I think I will add a config option to use unix timestamps instead.
