### ISSUE TITLE
Support for CentOS

### ISSUE THREAD

**Issue by mouwirth** [McLive/DjangoPowerDNS#2]
Hey, 

though this may be easy, can you add a tab for dependencies on CentOS?

**Comment by McLive** [comment]
Yeah I'll look into this although I never worked with CentOS

**Comment by santxus** [comment]
Hi any news about this? I'm really interested in CentOS7

**Comment by mouwirth** [comment]
#5

**Comment by McLive** [comment]
Thanks again to @mouwirth for solving his own issue. 🥇
