### ISSUE TITLE
How do I start it?

### ISSUE THREAD

**Issue by fenice2** [McLive/DjangoPowerDNS#3]
Hi

Sorry about the novice question but I'm looking to replace poweradmin to manage my DNS server and came upon your project today. I've followed the instruction to ionstall this on my CentOS7 server, it all went  OK and after getting to the end of the instruction and running the migrate and superuser I suddenly realised there isn't any mention of how to start this application. I'm totally new to both python or Django, I'm guessing it's something blindingly obvious that I've missed.

Regards

Bill

**Comment by McLive** [comment]
Hi,

you can start the dev-server with `python manage.py runserver 0.0.0.0:8000` but to use it in a production environment you may want to use some wsgi server like uwsgi.

Check this page for more help with that: https://docs.djangoproject.com/en/1.11/howto/deployment/wsgi/uwsgi/

**Comment by fenice2** [comment]
Hi

Thanks for the quick response and that doc link, I'll give this a run later.

Best wishes for a happy and prosperous New Year. :)


Bill
