### ISSUE TITLE
Bad Request (400)

### ISSUE THREAD

**Issue by AysadKozanoglu** [McLive/DjangoPowerDNS#35]
_python manage.py runserver_ 

<pre>
...
System check identified no issues (0 silenced).
December 10, 2019 - 21:00:24
Django version 1.11.23, using settings 'DjangoPowerDNS.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
...
</pre>

while opening 127.0.0.1:8000 over web get following error:

<pre>
Bad Request (400)
</pre>

**Comment by McLive** [comment]
Have you added your hostname to the ALLOWED_HOSTS list in settings.py?

Try settings DEBUG to True if the issue still exists.

**Comment by AysadKozanoglu** [comment]
solved:
edit the file 
vim DjangoPowerDNS/settings.py

and change the the following lines for your needs (allow hosts)

<pre>
...
ALLOWED_HOSTS = [
    u'i.am.allowed.host'
]
...
</pre>

change to 
<pre>
ALLOWED_HOSTS = ['*']
</pre>

notice:  * to match any host  (use only for development or test environment) 

better (nice): it is better to run nginx as web proxy to forward requests upstream to  127.0.0.1:8000 and let django allow only 127.0.0.1 (see above lines and replace * with 127.0.0.1 )

**Comment by AysadKozanoglu** [comment]
solved:
edit the file 
<pre>
DjangoPowerDNS/settings.py
</pre>

and change the the following lines for your needs (allow hosts)

<pre>
...
ALLOWED_HOSTS = [
    u'i.am.allowed.host'
]
...
</pre>

change to 
<pre>
ALLOWED_HOSTS = ['*']
</pre>

notice:  * to match any host  (use only for development or test environment) 

better (nice): it is better to run nginx as web proxy to forward requests upstream to  127.0.0.1:8000 and let django allow only 127.0.0.1 (see above lines and replace * with 127.0.0.1 )
