### ISSUE TITLE
HTTP 400 Error

### ISSUE THREAD

**Issue by michalzimniak** [McLive/DjangoPowerDNS#4]
Hi,

Just started the server for tests using command:

`# python manage.py runserver 0.0.0.0:8000`

and get:

Performing system checks...

```
System check identified no issues (0 silenced).
January 26, 2018 - 23:22:13
Django version 1.11.3, using settings 'DjangoPowerDNS.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[26/Jan/2018 23:22:19] "GET / HTTP/1.1" 400 26
[26/Jan/2018 23:22:20] "GET / HTTP/1.1" 400 26
[26/Jan/2018 23:24:55] "GET / HTTP/1.1" 400 26
[26/Jan/2018 23:24:56] "GET / HTTP/1.1" 400 26
[26/Jan/2018 23:24:57] "GET / HTTP/1.1" 400 26
[26/Jan/2018 23:25:02] "GET /index HTTP/1.1" 400 26
```

![image](https://user-images.githubusercontent.com/7513244/35465316-6c1e9818-02fb-11e8-9603-8617b46f0d00.png)

Any ideas how to fix it?

**Comment by McLive** [comment]
Have you applied the migrations using `python manage.py migrate`?

Please turn on the debug mode in settings.py
``DEBUG = True``

This will print some more useful error messages,

**Comment by McLive** [comment]
Thats weird. Have you tried clearing the cache with CTRL + F5 to reload the page?
Are there any errors left in the python console?

**Comment by michalzimniak** [comment]
I tried shift+F5 ;)

No other errors in python console...
Need to use bower?

**Comment by McLive** [comment]
No you don't have to use bower..

Can you show me the output of **/static/bootstrap-4.0.0-beta/dist/css/bootstrap.min.css**?
And also the response headers of that request. Should look like

`Content-Length:21781
Content-Type:text/html; charset=utf-8
Date:Sat, 27 Jan 2018 21:26:36 GMT
Server:WSGIServer/0.1 Python/2.7.9`

**Comment by michalzimniak** [comment]
There is no bootstrap.min.css file in /static/bootstrap-4.0.0-beta, because there is no dist dir...

**Comment by McLive** [comment]
Oh wow, these files were missing in the github repository. 
Thanks for pointing this out. Please try again now by updating with git pull.

**Comment by michalzimniak** [comment]
Ahhh, I just wondered why you didnt add those files to repo, that's why I asked about bower.
Now its OK, thanks. Great support .

Please close this issue ;)

**Comment by McLive** [comment]
Yeah the .gitignore from bootstrap made git ignoring it. :)

Great it's now working for you.
